name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]  # Tests run on PRs but no deployment
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Add permissions needed for OIDC token
    permissions:
      contents: read
      id-token: write

    steps:
      # Checkout code with authentication for private repo
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Use the built-in GITHUB_TOKEN for authentication
          token: ${{ secrets.GITHUB_TOKEN }}
          # If you need to checkout submodules in private repos
          submodules: 'recursive'
      
      - name: Replace API endpoint placeholder in HTML file
        run: |
          find . -name "*.html" -type f -exec sed -i "s|%%API_ENDPOINT%%|${{ secrets.API_ENDPOINT }}|g" {} +

      # Configure AWS credentials using OIDC role
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::730335547410:role/GitHubActions_cloud_resume_challenge_website
          role-session-name: GitHubActions-cloud_resume_challenge_website-${{ github.run_id }}
          aws-region: us-east-1

      - name: S3 Sync
        run: |
          aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} --follow-symlinks --delete

      - name: CloudFront Invalidation
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION }} --paths "/*"

      - name: Wait 30 seconds to allow cache invalidation to complete
        run: sleep 30s
        shell: bash
